[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 1

[window.padding]
x = 25
y = 20

[font]
size = 15.0

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Medium Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[general]

live_config_reload = true
import = [
    "~/.config/alacritty/themes/tokyo-night-storm.toml"
]

